---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive repository view
  description: >
    This view combines both in-vehicle and off-vehicle automotive
    workloads into a single view, representing the automotive
    repository.
  # Contacts: psabata, ssmoogen
  maintainer: automotive-base-enablement
  labels:
    - automotive
  repository: automotive-repositories-c9s
